### ISSUE TITLE
Auction house cli -> Transaction failed: Custom program error: 0x7d0 when trying to buy an NFT

### ISSUE THREAD

**Issue by teseo** [metaplex-foundation/metaplex-program-library#258]
Hi, 

I'm following the steps in the [auction house cli documentation page](https://docs.metaplex.com/auction-house/cli) and so far I can create an auction house, I can put an NFT for sale but when I try to buy, literally copy and pasting what's in the documentation and replacing it with the wallet id's and nft address of my tests, I'm having his issue 

```
ts-node src/auction-house-cli.ts buy -k ~/my-solana-wallets/BUuMFvfvuMRewCqSkdRCCxJNfUeSXxJC28Mf7e8wnrpQ.json -ah vTYx4QY77xprhR5v8swJyejWJLw2jFC1r1TtmBnhvsn --buy-price 1 --token-size 1 --mint BHKdnsPetFU8VrZjfAyVB6PA2xjd9HmJNCm7THcVZt1Y
wallet public key: BUuMFvfvuMRewCqSkdRCCxJNfUeSXxJC28Mf7e8wnrpQ
Rejected via websocket { InstructionError: [ 0, { Custom: 2000 } ] }
Timeout Error caught {
  err: { InstructionError: [ 0, [Object] ] },
  slot: 117725053,
  confirmations: 0
}
(node:4862) UnhandledPromiseRejectionWarning: Error: Transaction failed: Custom program error: 0x7d0
    at sendSignedTransaction (~/workspace/metaplex/js/packages/cli/src/helpers/transactions.ts:136:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async sendTransactionWithRetryWithKeypair (~/workspace/metaplex/js/packages/cli/src/helpers/transactions.ts:59:26)
    at async Command.<anonymous> (~/workspace/metaplex/js/packages/cli/src/auction-house-cli.ts:1042:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4862) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)
(node:4862) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I understand 0x7d0 is error 2000 and as in https://github.com/project-serum/anchor/blob/master/lang/src/error.rs#L41 it says 
```
    /// 2000 - A mut constraint was violated
    #[msg("A mut constraint was violated")]
    ConstraintMut = 2000,
```

I am a bit lost as this implies an account might not be marked as `mut` but the `auction-house-cli` should have taken care of this?

**Comment by C4B4D4** [comment]
Did you ever find out what was the problem? I'm having exactly the same error.

**Comment by C4B4D4** [comment]
I figured out that this gets resolved in the latest versions of the **@metaplex-foundation/mpl-auction-house** library. Which happens to be 2.1.1 at this moment.
