### ISSUE TITLE
[Bug]: Class Object is missing in schema: data.data 

### ISSUE THREAD

**Issue by AlexLeung** [metaplex-foundation/metaplex-program-library#307]
### Which package is this bug report for?

token-metadata

### Issue description

`import {programs as Metaplex} from '@metaplex/js';`  
then construct `Metaplex.metadata.UpdateMetadataV2` with any valid `metadataData` field

Example:

```typescript
const pk = Keypair.generate().publicKey;
new Metaplex.metadata.UpdateMetadataV2({
  recentBlockhash: "",
  feePayer: pk
}, {
  metadata: pk,
  updateAuthority: pk,
  metadataData: {
    name: "",
    symbol: "",
    uri: "",
    sellerFeeBasisPoints: 500,
    creators: [],
    uses: null,
    collection: null
  },
});
```

then we get issue below. This seems to work with all `metadataData` inputs I can come up with. Issue only goes away when I remove the `metadataData` field entirely.

This should be high priority because it renders the entire `UpdateMetadataV2` SDK unusable.

### Relevant log output

```shell
Error: Class Object is missing in schema: data.data
      at serializeStruct (node_modules\borsh\lib\index.js:296:15)
      at serializeField (node_modules\borsh\lib\index.js:283:13)
      at serializeField (node_modules\borsh\lib\index.js:275:25)
      at D:\Projects\space-bums\space-bums\node_modules\borsh\lib\index.js:300:13
      at Array.map (<anonymous>)
      at serializeStruct (node_modules\borsh\lib\index.js:299:29)
      at serialize (node_modules\borsh\lib\index.js:322:5)
      at Function.serialize (node_modules\@metaplex-foundation\mpl-core\src\utils\borsh.ts:66:33)
      at new UpdateMetadataV2 (node_modules\@metaplex-foundation\mpl-token-metadata\src\transactions\UpdateMetadataV2.ts:52:39)
      at D:\Projects\space-bums\space-bums\apps\solana-program\tests\solana-program.ts:100:22
      at Generator.next (<anonymous>)
      at fulfilled (apps\solana-program\node_modules\tslib\tslib.js:114:62)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

### Priority this issue should have

High (immediate attention needed)

**Comment by AlexLeung** [comment]
Relevant code link from within Borsh https://github.com/near/borsh-js/blob/master/borsh-ts/index.ts#L314-L323

Seems like the Metaplex Lib is not registering the DataV2 Schema properly.

**Comment by AlexLeung** [comment]
So it's not that the DataV2 isn't registered, actually it's hinted at by the error, seems like we can't use an Object literal as the value of the `metadataData` field.
Solution: we need to use the `DataV2` class constructor. So this code works

```typescript
import * as Metaplex from '@metaplex/js';
const pk = Keypair.generate().publicKey;
new Metaplex.programs.metadata.UpdateMetadataV2({
  recentBlockhash: "",
  feePayer: pk
}, {
  metadata: pk,
  updateAuthority: pk,
  metadataData: new Metaplex.programs.metadata.DataV2({
    name: "",
    symbol: "",
    uri: "",
    sellerFeeBasisPoints: 500,
    creators: [],
    uses: null,
    collection: null
  }),
});
```

I would say this is mostly an issue with Metaplex documentation and a fundamental flaw in the API enforced by Borsh. Closing this since since things aren't actually broken here.
