### ISSUE TITLE
[Bug]: candy machine v2's verify_assets CLI miscounts images in current directory

### ISSUE THREAD

**Issue by sfdz** [metaplex-foundation/metaplex-program-library#364]
### Which package is this bug report for?

candy-machine

### Issue description

The `verify_assets` command has an off-by-one error when it counts the number of images in the current directory.

Steps to reproduce:
* Create a directory with nft metadata, in my case 100 items
* Verify that the number of files is correct
```
% ls | wc -w
     200
```
* Run verify_assets from within that directory
```
% npx ts-node ~/Documents/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts verify_assets .
```

### Relevant log output

```shell
started at: 1649430876934
/Users/sfdz/Documents/metaplex/js/packages/cli/src/commands/verifyTokenMetadata/index.ts:27
    throw new Error(
          ^
Error: number of img files (101) is different than the number of json files (100)
    at verifyAssets (/Users/sfdz/Documents/metaplex/js/packages/cli/src/commands/verifyTokenMetadata/index.ts:27:11)
    at verifyTokenMetadata (/Users/sfdz/Documents/metaplex/js/packages/cli/src/commands/verifyTokenMetadata/index.ts:166:15)
    at Command.<anonymous> (/Users/sfdz/Documents/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts:331:24)
    at Command.listener [as _actionHandler] (/Users/sfdz/Documents/metaplex/js/packages/cli/node_modules/commander/lib/command.js:488:17)
    at /Users/sfdz/Documents/metaplex/js/packages/cli/node_modules/commander/lib/command.js:1227:65
    at Command._chainOrCall (/Users/sfdz/Documents/metaplex/js/packages/cli/node_modules/commander/lib/command.js:1144:12)
    at Command._parseCommand (/Users/sfdz/Documents/metaplex/js/packages/cli/node_modules/commander/lib/command.js:1227:27)
    at Command._dispatchSubcommand (/Users/sfdz/Documents/metaplex/js/packages/cli/node_modules/commander/lib/command.js:1050:25)
    at Command._parseCommand (/Users/sfdz/Documents/metaplex/js/packages/cli/node_modules/commander/lib/command.js:1193:19)
    at Command.parse (/Users/sfdz/Documents/metaplex/js/packages/cli/node_modules/commander/lib/command.js:897:10)
```

### Priority this issue should have

Low (slightly annoying)

**Comment by sfdz** [comment]
The CLI isn't contained in this repo
