### ISSUE TITLE
[Bug]: ERR_OUT_OF_RANGE when using Metadata.fromAccountAddress()

### ISSUE THREAD

**Issue by Adomas-Alimas** [metaplex-foundation/metaplex-program-library#618]
### Which package is this bug report for?

token-metadata

### Which Type of Package is this bug report for?

JS SDK

### Issue description

Hi, I have encountered an issues when using `Metadata.fromAccountAddress()` function to gather token metadata.
This is my code:
```
import { Connection, PublicKey } from '@solana/web3.js';
import { Metadata } from '@metaplex-foundation/mpl-token-metadata';

const CONN = new Connection('https://rpc.ankr.com/solana');

export async function getTokenInfo(address: string): Promise<void> {
    const pubKey = new PublicKey(address)
    await Metadata.fromAccountAddress(CONN, pubKey);
}

getTokenInfo('SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt').then();
```
Seems that the offset passed to the internal `.deserialize` method is wrong/corrupted. Thanks for any help.

### Relevant log output

```shell
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 78. Received 207935148
    at new NodeError (node:internal/errors:363:5)
    at boundsError (node:internal/buffer:86:9)
    at Buffer.readUInt32LE (node:internal/buffer:220:5)
    at Object.read (/Users/admin/code/sol-token-metadata/node_modules/@metaplex-foundation/beet/src/beets/numbers.ts:51:16)
    at Object.toFixedFromData (/Users/admin/code/sol-token-metadata/node_modules/@metaplex-foundation/beet/src/beets/string.ts:55:21)
    at fixBeetFromData (/Users/admin/code/sol-token-metadata/node_modules/@metaplex-foundation/beet/src/beet.fixable.ts:22:17)
    at FixableBeetArgsStruct.toFixedFromData (/Users/admin/code/sol-token-metadata/node_modules/@metaplex-foundation/beet/src/struct.fixable.ts:85:40)
    at FixableBeetArgsStruct.deserialize (/Users/admin/code/sol-token-metadata/node_modules/@metaplex-foundation/beet/src/struct.fixable.ts:59:17)
    at Object.deserialize (/Users/admin/code/sol-token-metadata/node_modules/@metaplex-foundation/mpl-token-metadata/src/custom/metadata-deserializer.ts:39:38)
    at Function.deserialize (/Users/admin/code/sol-token-metadata/node_modules/@metaplex-foundation/mpl-token-metadata/src/generated/accounts/Metadata.ts:120:12) {
  code: 'ERR_OUT_OF_RANGE'
}
```

### Priority this issue should have

Medium (should be fixed soon)

**Comment by Adomas-Alimas** [comment]
Nvm, I was passing token public key and not the PDA to Metadata.fromAccountAddress(). Passing the PDA returns correct data, now the only question is how would I get the PDA with using deprecated functions? This is what I am doing currently:

```
import { Metadata } from '@metaplex-foundation/mpl-token-metadata';
import { deprecated } from "@metaplex-foundation/mpl-token-metadata";
const PDA = await deprecated.Metadata.getPDA(pubKey);
const metadata = (await Metadata.fromAccountAddress(CONN, PDA)).data;
```

**Comment by FME849** [comment]
> Nvm, I was passing token public key and not the PDA to Metadata.fromAccountAddress(). Passing the PDA returns correct data, now the only question is how would I get the PDA with using deprecated functions? This is what I am doing currently:
> 
> ```
> import { Metadata } from '@metaplex-foundation/mpl-token-metadata';
> import { deprecated } from "@metaplex-foundation/mpl-token-metadata";
> const PDA = await deprecated.Metadata.getPDA(pubKey);
> const metadata = (await Metadata.fromAccountAddress(CONN, PDA)).data;
> ```

This is how I get the PDA: 
```
import { Pda } from '@metaplex-foundation/js';
import { PROGRAM_ID } from '@metaplex-foundation/mpl-token-metadata';
import { PublicKey } from '@solana/web3.js';
const METADATA_PROGRAM_ID = new PublicKey('metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s');
const pda = Pda.find(
        PROGRAM_ID,
        [Buffer.from('metadata'), METADATA_PROGRAM_ID.toBuffer(), mintAddress.toBuffer()]
```
Hope it's help
