### ISSUE TITLE
[Bug]: Listing issue with Auctioneer Contract

### ISSUE THREAD

**Issue by samia-invozone** [metaplex-foundation/metaplex-program-library#836]
### Which package is this bug report for?

auction-house

### Which Type of Package is this bug report for?

Rust Contract

### Issue description

I have executed the cancel list instruction on Auctioneer Program. It got canceled successfully but I'm no more able to list the same NFT again. Can you guys please check this issue? I'm also sharing transactions of 1st time listing & cancel listing and getting the below-mentioned error when trying to list again.

[Listing Transaction]
**(https://solscan.io/tx/64y8eCaUGWva7Q5WekAjUfTEgGbEWq9JohFCVAgmADwWFLk3n4xV5zPb9zTfRxrAXSfVWPNwSAev1hhs91u2ixL6?cluster=devnet)**

[Cancel Listing Transaction]**(https://solscan.io/tx/4fNJssmZkVq98gH3jDSCDQq1Wj7H8whifX9598nWKgYrP7p8ekztpex3yZHTwP8hKQ5p8M7nCZCVkw3MxMPays53?cluster=devnet)**

### Relevant log output

```shell
Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x0
    at Connection.sendEncodedTransaction (connection.ts:5024:1)
    at async Connection.sendRawTransaction (connection.ts:4983:1)
    at async sellFunction (Sell.tsx:173:1)
```

### Priority this issue should have

High (immediate attention needed)

**Comment by danenbm** [comment]
This should be fixed by: https://github.com/metaplex-foundation/metaplex-program-library/pull/814

**Comment by samia-invozone** [comment]
@danenbm #814 PR is merged or not??

**Comment by samuelvanderwaal** [comment]
> @danenbm #814 PR is merged or not??

It's merged, but not deployed yet. We will be deploying a new version later today.
