### ISSUE TITLE
[Bug]: Auction house's direct buy operation fails at mainnet.

### ISSUE THREAD

**Issue by surenzeroonelabs** [metaplex-foundation/metaplex-program-library#872]
### Which package is this bug report for?

auction-house

### Which Type of Package is this bug report for?

Rust Contract

### Issue description

We have been trying to build a market place using `Metaplex Auction House`.  At the moment we are using `@metaplex-foundation/js` version `0.17.3`.  We have been directly using the operation functions here `https://github.com/metaplex-foundation/js/tree/main/packages/js/src/plugins/auctionHouseModule/operations` . So far we have been successful at `listing` a NFT but unsuccessful at making a `directBuy`. We get following exception from the netwrok

```json
{
    "logs": [
        "Program hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk invoke [1]",
        "Program log: Instruction: Buy",
        "Program 11111111111111111111111111111111 invoke [2]",
        "Program 11111111111111111111111111111111 success",
        "Program log: Transfer 897840 lamports to the new account",
        "Program 11111111111111111111111111111111 invoke [2]",
        "Program 11111111111111111111111111111111 success",
        "Program log: Allocate space for the account BcvXsdneMBz5CcSA9xfZ1BqHCDExPj6sJ3vQGULD4VvK",
        "Program 11111111111111111111111111111111 invoke [2]",
        "Program 11111111111111111111111111111111 success",
        "Program log: Assign the account to the owning program",
        "Program 11111111111111111111111111111111 invoke [2]",
        "Program 11111111111111111111111111111111 success",
        "Program log: Completed assignation!",
        "Program hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk consumed 70682 of 800000 compute units",
        "Program hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk success",
        "Program hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk invoke [1]",
        "Program log: Instruction: PrintBidReceipt",
        "Program log: Transfer 2763120 lamports to the new account",
        "Program 11111111111111111111111111111111 invoke [2]",
        "Program 11111111111111111111111111111111 success",
        "Program log: Allocate space for the account 269As4VuBG9uQAsQZxoZh53AiuuwCoxtPz52jzxfSLvz",
        "Program 11111111111111111111111111111111 invoke [2]",
        "Program 11111111111111111111111111111111 success",
        "Program log: Assign the account to the owning program",
        "Program 11111111111111111111111111111111 invoke [2]",
        "Program 11111111111111111111111111111111 success",
        "Program log: Completed assignation!",
        "Program hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk consumed 28878 of 729318 compute units",
        "Program hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk success",
        "Program hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk invoke [1]",
        "Program log: Instruction: ExecuteSale",
        "Program 11111111111111111111111111111111 invoke [2]",
        "Program 11111111111111111111111111111111 success",
        "Program 11111111111111111111111111111111 invoke [2]",
        "Program 11111111111111111111111111111111 success",
        "Program 11111111111111111111111111111111 invoke [2]",
        "Program 11111111111111111111111111111111 success",
        "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [2]",
        "Program log: Create",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [3]",
        "Program log: Instruction: GetAccountDataSize",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1595 of 629425 compute units",
        "Program return: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA pQAAAAAAAAA=",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success",
        "Program 11111111111111111111111111111111 invoke [3]",
        "Program 11111111111111111111111111111111 success",
        "Program log: Initialize the associated token account",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [3]",
        "Program log: Instruction: InitializeImmutableOwner",
        "Program log: Please upgrade to SPL Token 2022 for immutable owner support",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1405 of 622962 compute units",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [3]",
        "Program log: Instruction: InitializeAccount3",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4214 of 619080 compute units",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success",
        "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 20239 of 634822 compute units",
        "Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL success",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [2]",
        "Program log: Instruction: Transfer",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 4735 of 608811 compute units",
        "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA success",
        "Program hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk consumed 98753 of 700440 compute units",
        "Program hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk success",
        "Program hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk invoke [1]",
        "Program log: Instruction: PrintPurchaseReceipt",
        "Program log: Transfer 2234160 lamports to the new account",
        "Program 11111111111111111111111111111111 invoke [2]",
        "Program 11111111111111111111111111111111 success",
        "Program log: Allocate space for the account 7FbTxmZFQ6MGXE25yBUQahYRt1G9t9q4JUxzoKRXiQER",
        "Program 11111111111111111111111111111111 invoke [2]",
        "Program 11111111111111111111111111111111 success",
        "Program log: Assign the account to the owning program",
        "Program 11111111111111111111111111111111 invoke [2]",
        "Program 11111111111111111111111111111111 success",
        "Program log: Completed assignation!",
        "Program hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk consumed 38862 of 601687 compute units",
        "Program hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk success"
    ],
    "stacktrace": [
        "Error: failed to send transaction: Transaction simulation failed: Transaction results in an account (9) without insufficient funds for rent",
        "    at Connection9.sendEncodedTransaction (/var/task/index.js:109144:17)",
        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
        "    at async Connection9.sendRawTransaction (/var/task/index.js:109115:24)",
        "    at async sendAndConfirmRawTransaction3 (/var/task/index.js:111194:26)",
        "    at async directBuy (/var/task/index.js:284736:17)"
    ],
    "message": "failed to send transaction: Transaction simulation failed: Transaction results in an account (9) without insufficient funds for rent",
    "locations": [
        {
            "line": 1,
            "column": 66
        }
    ],
    "path": [
        "directBuy"
]
}

```

The transaction instructions that threw above exception are
```json
[
  {
    "keys": [
      {
        "pubkey": "5C8iqUAAHnDdfngSf5pdCZsAznRCnzpo3JhtZyrniQ46",
        "isSigner": true,
        "isWritable": false
      },
      {
        "pubkey": "5C8iqUAAHnDdfngSf5pdCZsAznRCnzpo3JhtZyrniQ46",
        "isSigner": false,
        "isWritable": true
      },
      {
        "pubkey": "5C8iqUAAHnDdfngSf5pdCZsAznRCnzpo3JhtZyrniQ46",
        "isSigner": false,
        "isWritable": false
      },
      {
        "pubkey": "So11111111111111111111111111111111111111112",
        "isSigner": false,
        "isWritable": false
      },
      {
        "pubkey": "7xzrbr99p1egdgFyzHXEGn7i7k1qR4XNnc8BU7TPhpvw",
        "isSigner": false,
        "isWritable": false
      },
      {
        "pubkey": "AtWm9WSJRkM3VBWZg1Mo6KNTv3STpEAgCkj9hkDjA1Hv",
        "isSigner": false,
        "isWritable": false
      },
      {
        "pubkey": "65XqYSRjH2GUULoqz8AkhkQtgdBw55nCuKzFKyDWNN4q",
        "isSigner": false,
        "isWritable": true
      },
      {
        "pubkey": "G2bhxo6ED2JToTdLEYLEZjbTh1mgjGojUByDRMXwKHjN",
        "isSigner": false,
        "isWritable": false
      },
      {
        "pubkey": "5zAqHrE2SdCpsJDFLrY7Yv2rQ7xDMX175vMgtDrXkkp9",
        "isSigner": false,
        "isWritable": false
      },
      {
        "pubkey": "8oyiAmKBqyNR5vSgfrDii9QtuY62RG5DmpoTUxyNiU7g",
        "isSigner": false,
        "isWritable": true
      },
      {
        "pubkey": "BcvXsdneMBz5CcSA9xfZ1BqHCDExPj6sJ3vQGULD4VvK",
        "isSigner": false,
        "isWritable": true
      },
      {
        "pubkey": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        "isSigner": false,
        "isWritable": false
      },
      {
        "pubkey": "11111111111111111111111111111111",
        "isSigner": false,
        "isWritable": false
      },
      {
        "pubkey": "SysvarRent111111111111111111111111111111111",
        "isSigner": false,
        "isWritable": false
      }
    ],
    "programId": "hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk",
    "data": [
      102,
      6,
      61,
      18,
      1,
      218,
      235,
      234,
      249,
      255,
      0,
      45,
      49,
      1,
      0,
      0,
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ]
  },
  {
    "keys": [
      {
        "pubkey": "269As4VuBG9uQAsQZxoZh53AiuuwCoxtPz52jzxfSLvz",
        "isSigner": false,
        "isWritable": true
      },
      {
        "pubkey": "5C8iqUAAHnDdfngSf5pdCZsAznRCnzpo3JhtZyrniQ46",
        "isSigner": true,
        "isWritable": true
      },
      {
        "pubkey": "11111111111111111111111111111111",
        "isSigner": false,
        "isWritable": false
      },
      {
        "pubkey": "SysvarRent111111111111111111111111111111111",
        "isSigner": false,
        "isWritable": false
      },
      {
        "pubkey": "Sysvar1nstructions1111111111111111111111111",
        "isSigner": false,
        "isWritable": false
      }
    ],
    "programId": "hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk",
    "data": [
      94,
      249,
      90,
      230,
      239,
      64,
      68,
      218,
      254
    ]
  },
  {
    "keys": [
      {
        "pubkey": "5C8iqUAAHnDdfngSf5pdCZsAznRCnzpo3JhtZyrniQ46",
        "isSigner": false,
        "isWritable": true
      },
      {
        "pubkey": "HpJECxUssMfLAnDExD1vNh5QJuVp8NgvvjbMtbgJGWgT",
        "isSigner": false,
        "isWritable": true
      },
      {
        "pubkey": "7xzrbr99p1egdgFyzHXEGn7i7k1qR4XNnc8BU7TPhpvw",
        "isSigner": false,
        "isWritable": true
      },
      {
        "pubkey": "J5UUVPt6EqGbgkSeoG66Q8rA9FgNdjxp9xGMcGqU2D74",
        "isSigner": false,
        "isWritable": false
      },
      {
        "pubkey": "AtWm9WSJRkM3VBWZg1Mo6KNTv3STpEAgCkj9hkDjA1Hv",
        "isSigner": false,
        "isWritable": false
      },
      {
        "pubkey": "So11111111111111111111111111111111111111112",
        "isSigner": false,
        "isWritable": false
      },
      {
        "pubkey": "65XqYSRjH2GUULoqz8AkhkQtgdBw55nCuKzFKyDWNN4q",
        "isSigner": false,
        "isWritable": true
      },
      {
        "pubkey": "HpJECxUssMfLAnDExD1vNh5QJuVp8NgvvjbMtbgJGWgT",
        "isSigner": false,
        "isWritable": true
      },
      {
        "pubkey": "G5ixLSeaPGvCwinLPtvGHhequQpEu5NGgD5nFVokdB5d",
        "isSigner": false,
        "isWritable": true
      },
      {
        "pubkey": "G2bhxo6ED2JToTdLEYLEZjbTh1mgjGojUByDRMXwKHjN",
        "isSigner": false,
        "isWritable": false
      },
      {
        "pubkey": "5zAqHrE2SdCpsJDFLrY7Yv2rQ7xDMX175vMgtDrXkkp9",
        "isSigner": false,
        "isWritable": false
      },
      {
        "pubkey": "8oyiAmKBqyNR5vSgfrDii9QtuY62RG5DmpoTUxyNiU7g",
        "isSigner": false,
        "isWritable": true
      },
      {
        "pubkey": "B931x9A4FPuemi2oCSauJy1fjRmPwuxM9xbLtM8Zg8Kj",
        "isSigner": false,
        "isWritable": true
      },
      {
        "pubkey": "BcvXsdneMBz5CcSA9xfZ1BqHCDExPj6sJ3vQGULD4VvK",
        "isSigner": false,
        "isWritable": true
      },
      {
        "pubkey": "GAaTFXp5epCJizF4Apb5cPDKyqa58w7e72sqdsmUGBYw",
        "isSigner": false,
        "isWritable": true
      },
      {
        "pubkey": "3csMJSyDQtayMzDQ1WkBEberQ4jTNftbjHduLQZcsYkK",
        "isSigner": false,
        "isWritable": true
      },
      {
        "pubkey": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        "isSigner": false,
        "isWritable": false
      },
      {
        "pubkey": "11111111111111111111111111111111",
        "isSigner": false,
        "isWritable": false
      },
      {
        "pubkey": "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",
        "isSigner": false,
        "isWritable": false
      },
      {
        "pubkey": "HS2eL9WJbh7pA4i4veK3YDwhGLRjY3uKryvG1NbHRprj",
        "isSigner": false,
        "isWritable": false
      },
      {
        "pubkey": "SysvarRent111111111111111111111111111111111",
        "isSigner": false,
        "isWritable": false
      },
      {
        "pubkey": "27F51HE5PEMKvr6QPcV3GNaZz7W6G527Wvg4zYAg24Sh",
        "isSigner": false,
        "isWritable": true
      }
    ],
    "programId": "hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk",
    "data": [
      37,
      74,
      217,
      157,
      79,
      49,
      35,
      6,
      255,
      255,
      255,
      0,
      45,
      49,
      1,
      0,
      0,
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ]
  },
  {
    "keys": [
      {
        "pubkey": "7FbTxmZFQ6MGXE25yBUQahYRt1G9t9q4JUxzoKRXiQER",
        "isSigner": false,
        "isWritable": true
      },
      {
        "pubkey": "6NuGUqjc7YtZxTnnBaB9mKyNWgGpR57eMtRfNGSySm2",
        "isSigner": false,
        "isWritable": true
      },
      {
        "pubkey": "269As4VuBG9uQAsQZxoZh53AiuuwCoxtPz52jzxfSLvz",
        "isSigner": false,
        "isWritable": true
      },
      {
        "pubkey": "5C8iqUAAHnDdfngSf5pdCZsAznRCnzpo3JhtZyrniQ46",
        "isSigner": true,
        "isWritable": true
      },
      {
        "pubkey": "11111111111111111111111111111111",
        "isSigner": false,
        "isWritable": false
      },
      {
        "pubkey": "SysvarRent111111111111111111111111111111111",
        "isSigner": false,
        "isWritable": false
      },
      {
        "pubkey": "Sysvar1nstructions1111111111111111111111111",
        "isSigner": false,
        "isWritable": false
      }
    ],
    "programId": "hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk",
    "data": [
      227,
      154,
      251,
      7,
      180,
      56,
      100,
      143,
      255
    ]
  }
]
```

We are kind of clueless on why the transaction is failing. We have made sure the buyer, seller and auction house have enough balance.  The funny thing is we have automated test for this operation and it passes (We use `amman`  and `solana-test-validator` set up like this repo does).

Update:
Here is a similar transaction that failed.
https://solscan.io/tx/3yXa41amSECs1LWKepgwaG9nP9R1JPyerkon5UoCHbZ8qqMWn4rRPh4EveebX2dSjSGwEE6hD8wW6CKqmjVhNWEy

The account at index 9 is `8oyiAmKBqyNR5vSgfrDii9QtuY62RG5DmpoTUxyNiU7g` it is our `Auction House Fee Account`. Not sure why it has trouble executing the `directBuy` operation.

### Priority this issue should have

High (immediate attention needed)

**Comment by samuelvanderwaal** [comment]
@surenzeroonelabs can you confirm that this happens on the latest version on devnet, v1.3.2, deployed today?

**Comment by surenzeroonelabs** [comment]
I have a new theory. I am facing this issue because my `Auction House's Fee Account` address has 0 balance. In my local automated test, I had transferred few sol to my Auction House's fee account, otherwise the transaction would fail. When I try to transfer some Sol in `main-net` using my wallet, the wallet complains that the address of the `Fee Account` is not a valid Solana address. 
The address is ` 8oyiAmKBqyNR5vSgfrDii9QtuY62RG5DmpoTUxyNiU7g`, do you guys know what is the role of this account and how can I transfer some Sol to it?

**Comment by surenzeroonelabs** [comment]
Also found this in the doc https://docs.metaplex.com/programs/auction-house/cli#fee-account

```
Your Auction House fee account is used only when the Auction House authority is signing the transaction. This is usually only in the case of Requires Sign Off
```
But our `Auction House` does not requires `Sign Off`. Checkout the following details on our Auction House.

```
$ ts-node src/auction-house-cli.ts show -k ./auction-house-keypair.json -ah 5zAqHrE2SdCpsJDFLrY7Yv2rQ7xDMX175vMgtDrXkkp9 -e mainnet-beta
wallet public key: G2bhxo6ED2JToTdLEYLEZjbTh1mgjGojUByDRMXwKHjN
Using cluster mainnet-beta
No treasury mint detected, using SOL.
-----
Auction House: 5zAqHrE2SdCpsJDFLrY7Yv2rQ7xDMX175vMgtDrXkkp9
Mint: So11111111111111111111111111111111111111112
Authority: G2bhxo6ED2JToTdLEYLEZjbTh1mgjGojUByDRMXwKHjN
Creator: G2bhxo6ED2JToTdLEYLEZjbTh1mgjGojUByDRMXwKHjN
Fee Payer Acct: 8oyiAmKBqyNR5vSgfrDii9QtuY62RG5DmpoTUxyNiU7g
Treasury Acct: B931x9A4FPuemi2oCSauJy1fjRmPwuxM9xbLtM8Zg8Kj
Fee Payer Withdrawal Acct: G2bhxo6ED2JToTdLEYLEZjbTh1mgjGojUByDRMXwKHjN
Treasury Withdrawal Acct: G2bhxo6ED2JToTdLEYLEZjbTh1mgjGojUByDRMXwKHjN
Fee Payer Bal: 0
Treasury Bal: 0
Seller Fee Basis Points: 200
Requires Sign Off: false
Can Change Sale Price: false
AH Bump: 254
AH Fee Bump: 255
AH Treasury Bump: 253

```

**Comment by surenzeroonelabs** [comment]
`devnet` is unusable. The transaction keeps timing out hence cannot confirm if direct buy works in it.

**Comment by surenzeroonelabs** [comment]
Check https://github.com/metaplex-foundation/js/issues/385
